name: unittest analysis

on: 
  pull_request:
  workflow_dispatch:

concurrency:
 group: ${{ github.head_ref || github.ref_name }}
 cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  unittest:
    strategy:
      fail-fast: true
    timeout-minutes: 120
    runs-on: ubuntu-latest
    needs: [pre-commit]
    container:
      image: odoo:17
    services:
      postgres:
        image: postgres:14
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Testing the code with unittest
        run: odoo -i ${{ vars.INSTALL_ADDONS }} --test-enable --stop-after-init
